[project]
name = "webapp-deploy-lambda"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3==1.42.14",
]

[dependency-groups]
dev = [
    "ruff>=0.8.6",
]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["B", "C", "E", "F", "W", "B9"]

